# Generated by Django 4.0.4 on 2022-04-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherInCities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('temperature', models.SmallIntegerField(verbose_name='Температура')),
                ('weather', models.CharField(choices=[('Снег', 'Снег'), ('Дождь', 'Дождь'), ('Солнце', 'Солнце'), ('Облачность', 'Облачность')], max_length=50, verbose_name='Погода')),
            ],
            options={
                'verbose_name': 'Погода в городе',
                'verbose_name_plural': 'Погода в городах',
                'ordering': ('date', 'time'),
            },
        ),
    ]
