# Generated by Django 4.0.4 on 2022-04-22 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather_dashboard', '0003_alter_city_options_alter_city_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherincities',
            options={'ordering': ('date', 'hour'), 'verbose_name': 'Погода в городе', 'verbose_name_plural': 'Погода в городах'},
        ),
        migrations.AddField(
            model_name='weatherincities',
            name='hour',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24)], default=1, help_text='Выберете время (час)', verbose_name='Время(часы)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weatherincities',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_set', to='weather_dashboard.city', verbose_name='Город'),
        ),
        migrations.AlterUniqueTogether(
            name='weatherincities',
            unique_together={('city', 'date', 'hour')},
        ),
        migrations.RemoveField(
            model_name='weatherincities',
            name='time',
        ),
    ]
